### ISSUE TITLE
Fig5

### ISSUE THREAD

**Issue by cuijing111** [orhan-t/SM-CNN#3]
Can you give me Fig 5 relative code to show PSNR and SSIM line graph?
Thank you very much.

**Comment by orhan-t** [comment]
import scipy.io as io
import matplotlib.pyplot as plt
import numpy as np
from skimage.metrics import structural_similarity, peak_signal_noise_ratio
from sewar import full_ref as metric


lambda_x = [*np.linspace(0.4, 0.9, 52,endpoint=True), *np.linspace(1.4, 2.4, 139, endpoint=True)]
lambda_x = np.round(np.array(lambda_x),1)
x = np.array(np.arange(0, 191, 1))

# write your matlab file into ''
wdc_direction = './datssets/WDC/GT_crop.mat'
noise_direction = ''
LRMR_direction = ''
LRTF_DFR_direction = ''
LRTDTV_direction = ''
QRNN3D_direction = ''
HSID_CNN_direction = ''
MemNet_direction = ''
HDNET_direction = ''
MAN_direction = ''
SM_CNN_direction = ''

wdc = np.clip(np.array(io.loadmat(wdc_direction)['temp'][:, :, 0:191], dtype=np.float32), 0, 1)
noise = np.clip(np.array(io.loadmat(noise_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
LRMR = np.clip(np.array(io.loadmat(LRMR_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
LRTF_DFR = np.clip(np.array(io.loadmat(LRTF_DFR_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
LRTDTV = np.clip(np.array(io.loadmat(LRTDTV_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
QRNN3D = np.clip(np.array(io.loadmat(QRNN3D_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
HSID_CNN = np.clip(np.array(io.loadmat(HSID_CNN_direction)['data'][:, :, 0:191], dtype=np.float32), 0, 1)
MemNet = np.clip(np.array(io.loadmat(MemNet_direction)['data'][:, :, 0:191], dtype=np.float32), 0, 1)
HDNET = np.clip(np.array(io.loadmat(HDNET_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
MAN = np.clip(np.array(io.loadmat(MAN_direction)['R_hsi'][:, :, 0:191], dtype=np.float32), 0, 1)
SM_CNN = np.clip(np.array(io.loadmat(SM_CNN_direction)['data'][:, :, 0:191], dtype=np.float32), 0, 1)

band_num = wdc.shape[-1]

psnr_noisy = np.zeros(band_num,)
psnr_lrtf_dfr = np.zeros(band_num,)
psnr_lrmr = np.zeros(band_num,)
psnr_lrtdtv = np.zeros(band_num,)
psnr_qrnn3d = np.zeros(band_num,)
psrn_hsid_cnn = np.zeros(band_num,)
psrn_memnet = np.zeros(band_num,)
psrn_hdnet = np.zeros(band_num,)
psrn_man = np.zeros(band_num,)
psrn_sm_cnn = np.zeros(band_num,)

ssim_noisy = np.zeros(band_num,)
ssim_lrtf_dfr = np.zeros(band_num,)
ssim_lrmr = np.zeros(band_num,)
ssim_lrtdtv = np.zeros(band_num,)
ssim_qrnn3d = np.zeros(band_num,)
ssim_hsid_cnn = np.zeros(band_num,)
ssim_memnet = np.zeros(band_num,)
ssim_hdnet = np.zeros(band_num,)
ssim_man = np.zeros(band_num,)
ssim_sm_cnn = np.zeros(band_num,)


for i in range(band_num):
    psnr_noisy[i] = peak_signal_noise_ratio(wdc[..., i], noise[..., i])
    ssim_noisy[i] = structural_similarity(wdc[..., i], noise[..., i])
    psnr_lrtf_dfr[i] = peak_signal_noise_ratio(wdc[..., i], LRTF_DFR[..., i])
    ssim_lrtf_dfr[i] = structural_similarity(wdc[..., i], LRTF_DFR[..., i])
    psnr_lrmr[i] = peak_signal_noise_ratio(wdc[..., i], LRMR[..., i])
    ssim_lrmr[i] = structural_similarity(wdc[..., i], LRMR[..., i])
    psnr_lrtdtv[i] = peak_signal_noise_ratio(wdc[..., i], LRTDTV[..., i])
    ssim_lrtdtv[i] = structural_similarity(wdc[..., i], LRTDTV[..., i])
    psnr_qrnn3d[i] = peak_signal_noise_ratio(wdc[..., i], QRNN3D[..., i])
    ssim_qrnn3d[i] = structural_similarity(wdc[..., i], QRNN3D[..., i])
    psrn_hsid_cnn[i] = peak_signal_noise_ratio(wdc[..., i], HSID_CNN[..., i])
    ssim_hsid_cnn[i] = structural_similarity(wdc[..., i], HSID_CNN[..., i])
    psrn_memnet[i] = peak_signal_noise_ratio(wdc[..., i], MemNet[..., i])
    ssim_memnet[i] = structural_similarity(wdc[..., i], MemNet[..., i])
    psrn_hdnet[i] = peak_signal_noise_ratio(wdc[..., i], HDNET[..., i])
    ssim_hdnet[i] = structural_similarity(wdc[..., i], HDNET[..., i])
    psrn_man[i] = peak_signal_noise_ratio(wdc[..., i], MAN[..., i])
    ssim_man[i] = structural_similarity(wdc[..., i], MAN[..., i])
    psrn_sm_cnn[i] = peak_signal_noise_ratio(wdc[..., i], SM_CNN[..., i])
    ssim_sm_cnn[i] = structural_similarity(wdc[..., i], SM_CNN[..., i])

plt.figure(figsize=(16, 5))
plt.subplot(1,2,1)
plt.plot(psnr_lrmr, '-.', c='green', label='LRMR')
plt.plot(psnr_lrtdtv, '-', c='darkviolet', label='LRTDTV')
plt.plot(psnr_tdl, '-', c='yellow', label='LRTF-DFR')
plt.plot(psnr_qrnn3d, '-', c='black', label='QRNN3D')
plt.plot(psrn_hsid_cnn, '-',c='cyan', label='HSID-CNN')
plt.plot(psrn_memnet, '-',c='blue', label='MemNet')
plt.plot(psrn_hdnet, '.-',c='magenta', label='HDNET')
plt.plot(psrn_man, '.-',c='olive', label='MAN')
plt.plot(psrn_sm_cnn, c='red', label='SM-CNN')

plt.xticks(x, lambda_x, rotation='horizontal', fontsize=18)
plt.yticks(fontsize=18)
plt.locator_params(axis='x', nbins=12)
plt.xlim([0, 191])
plt.ylabel('PSNR (dB)', fontsize=18)
plt.xlabel('Wavelength ($\mu$m)', fontsize=18)
plt.legend(loc=3, fontsize=12)
plt.tight_layout()

plt.subplot(1,2,2)
plt.plot(ssim_lrmr, '-.', c='green', label='LRMR')
plt.plot(ssim_lrtdtv, '-', c='darkviolet', label='LRTDTV')
plt.plot(ssim_tdl, '-', c='yellow', label='LRTF-DFR')
plt.plot(ssim_qrnn3d, '-', c='black', label='QRNN3D')
plt.plot(ssim_hsid_cnn, '-',c='cyan', label='HSID-CNN')
plt.plot(ssim_memnet, '-',c='blue', label='MemNet')
plt.plot(ssim_hdnet, '.-',c='magenta', label='HDNET')
plt.plot(ssim_man, '.-',c='olive', label='MAN')
plt.plot(ssim_sm_cnn, c='red', label='SM-CNN')

plt.xticks(x, lambda_x, rotation='horizontal', fontsize=18)
plt.yticks(fontsize=18)
plt.locator_params(axis='x', nbins=12)
plt.xlim([0, 191])
plt.ylabel('SSIM', fontsize=18)
plt.xlabel('Wavelength ($\mu$m)', fontsize=18)

plt.legend(loc=3, fontsize=12)
plt.tight_layout()
plt.savefig("psnr_ssim.pdf", dpi=300)

plt.show()
